spdk_bdev_create RemoteNvme0n1
nvme_subsystem_create -s nqn.2026-09.io.snap:node4-remote-nvme1 -sn SNAPNODE3NVME1 -mn BlueField3-SNAP
nvme_namespace_create -s nqn.2026-09.io.snap:node4-remote-nvme1 -b RemoteNvme0n1 -n 1
nvme_controller_create -s nqn.2026-09.io.snap:node4-remote-nvme1 -c SnapCtrl0 --pf_id 0
nvme_controller_attach_ns -c SnapCtrl0 -n 1
